networks:
  app-network:
    driver: bridge

services:
  # AI Service container
  ai-service:
    image: ghcr.io/honeegee/brainbytesai/ai-service:${GITHUB_REF_NAME:-development}
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=staging
      - NODE_OPTIONS=--max_old_space_size=2048
      - API_KEY=${STAGING_AI_API_KEY}
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend container
  frontend:
    image: ghcr.io/honeegee/brainbytesai/frontend:${GITHUB_REF_NAME:-development}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=staging
      - NODE_OPTIONS=--max_old_space_size=1024
      - NEXT_PUBLIC_API_URL=https://api-staging.brainbytes.app
      - NEXT_PUBLIC_FRONTEND_URL=https://staging.brainbytes.app
    deploy:
      resources:
        limits:
          memory: 1G  
        reservations:
          memory: 512M  
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API container
  backend:
    image: ghcr.io/honeegee/brainbytesai/backend:${GITHUB_REF_NAME:-development}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - NODE_OPTIONS=--max_old_space_size=1024
      - DATABASE_URL=${STAGING_DATABASE_URL:-mongodb://mongo:27017/brainbytes_staging}
      - MONGODB_URI=${STAGING_DATABASE_URL:-mongodb://mongo:27017/brainbytes_staging}
      - JWT_SECRET=${STAGING_JWT_SECRET:-staging_jwt_secret_default_12345}
      - SESSION_SECRET=${STAGING_SESSION_SECRET:-staging_session_secret_default_12345}
    deploy:
      resources:
        limits:
          memory: 1G  
        reservations:
          memory: 512M  
    networks:
      - app-network
    depends_on:
      - ai-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# All services now connect to MongoDB Atlas
# No local database containers or volumes needed
volumes: {}