networks:
  app-network:
    driver: bridge

services:
  # AI Service container
  ai-service:
    build: ./ai-service
    ports:
      - "3002:3002"
    env_file:
      - ai-service/.env
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    volumes:
      - ./ai-service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  # Frontend container
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max_old_space_size=1024  
    deploy:
      resources:
        limits:
          memory: 1G  
        reservations:
          memory: 512M  
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules 
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped  

  # Backend API container
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    environment:
      - NODE_OPTIONS=--max_old_space_size=1024  
    deploy:
      resources:
        limits:
          memory: 1G  
        reservations:
          memory: 512M  
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - ai-service
    restart: unless-stopped

# All services now connect to MongoDB Atlas
# No local volumes needed for database
volumes: {}
