networks:
  app-network:
    driver: bridge

services:
  # AI Service container
  ai-service:
    build: ./ai-service
    ports:
      - "3002:3002"
    env_file:
      - ai-service/.env
    volumes:
      - ./ai-service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  # Frontend container
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  # Backend API container
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - mongo
      - ai-service
    restart: unless-stopped

  # MongoDB container
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

# Define volumes for persistent data
volumes:
  mongo-data:
