# Heroku Monitoring Stack Deployment
# This will deploy Prometheus and Grafana as separate Heroku apps

version: '3.8'

# Configuration for deploying monitoring to Heroku
services:
  prometheus-prod:
    build:
      context: ./monitoring
      dockerfile: Dockerfile.prometheus
    environment:
      - PORT=9090
      - HEROKU_APP_NAME=brainbytes-prometheus-prod
    
  grafana-prod:
    build:
      context: ./monitoring
      dockerfile: Dockerfile.grafana
    environment:
      - PORT=3000
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD=brainbytes
      - HEROKU_APP_NAME=brainbytes-grafana-prod

# Heroku Apps to create:
# 1. brainbytes-prometheus-prod - for metrics collection
# 2. brainbytes-grafana-prod - for dashboards