global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'brainbytes-staging@yourdomain.com'
  smtp_auth_username: 'brainbytes-staging@yourdomain.com'
  smtp_auth_password: 'your-email-password'

# Inhibition rules to prevent spam
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

# Routing configuration
route:
  group_by: ['alertname', 'instance', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 2h
  receiver: 'web.hook'
  
  routes:
  # Critical alerts - immediate notification
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 10s
    repeat_interval: 30m
    
  # Warning alerts - grouped notifications
  - match:
      severity: warning
    receiver: 'warning-alerts'
    group_wait: 30s
    group_interval: 10m
    repeat_interval: 2h
    
  # Info alerts - daily digest
  - match:
      severity: info
    receiver: 'info-alerts'
    group_wait: 5m
    group_interval: 1h
    repeat_interval: 24h

# Notification receivers
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/webhook'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'staging'
        password: 'webhook-password'

- name: 'critical-alerts'
  email_configs:
  - to: 'devops@yourdomain.com'
    subject: '[CRITICAL] BrainBytes Staging Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
      {{ if .GeneratorURL }}
      Source: {{ .GeneratorURL }}
      {{ end }}
      {{ end }}
    html: |
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; }
          .critical { color: #d32f2f; font-weight: bold; }
          .details { background-color: #f5f5f5; padding: 10px; margin: 10px 0; }
        </style>
      </head>
      <body>
        <h2 class="critical">🚨 CRITICAL ALERT - BrainBytes Staging</h2>
        {{ range .Alerts }}
        <div class="details">
          <h3>{{ .Annotations.summary }}</h3>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Instance:</strong> {{ .Labels.instance }}</p>
          <p><strong>Time:</strong> {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}</p>
          {{ if .GeneratorURL }}
          <p><a href="{{ .GeneratorURL }}">View in Prometheus</a></p>
          {{ end }}
        </div>
        {{ end }}
      </body>
      </html>

  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#brainbytes-alerts'
    title: '🚨 Critical Alert - BrainBytes Staging'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
      {{ end }}
    color: danger

- name: 'warning-alerts'
  email_configs:
  - to: 'dev-team@yourdomain.com'
    subject: '[WARNING] BrainBytes Staging Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
      {{ end }}

  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#brainbytes-monitoring'
    title: '⚠️ Warning - BrainBytes Staging'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Instance:* {{ .Labels.instance }}
      {{ end }}
    color: warning

- name: 'info-alerts'
  email_configs:
  - to: 'monitoring@yourdomain.com'
    subject: '[INFO] BrainBytes Staging Daily Report'
    body: |
      Daily monitoring report for BrainBytes Staging environment.
      
      {{ range .Alerts }}
      Info: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt.Format "2006-01-02 15:04:05 MST" }}
      {{ end }}

# Templates for custom formatting
templates:
- '/etc/alertmanager/templates/*.tmpl'