global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Production Heroku Apps
  - job_name: 'brainbytes-backend-production'
    static_configs:
      - targets: ['brainbytes-backend-production-d355616d0f1f.herokuapp.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'brainbytes-ai-production'
    static_configs:
      - targets: ['brainbytes-ai-production-3833f742ba79.herokuapp.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Scrape Staging Heroku Apps
  - job_name: 'brainbytes-backend-staging'
    static_configs:
      - targets: ['brainbytes-backend-staging-de872da2939f.herokuapp.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'brainbytes-ai-staging'
    static_configs:
      - targets: ['brainbytes-ai-service-staging-4b75c77cf53a.herokuapp.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Self-monitoring for production Prometheus
  - job_name: 'prometheus-production'
    static_configs:
      - targets: ['brainbytes-prometheus-prod-e140dc0c840c.herokuapp.com:443']
    scheme: https
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s